Repository green-code-initiative/creedengo-javascript, pull requests merged in 2025-01, with the labels that each got.

#58 Show support for SonarQube 25.1
  CHANGELOG.md
  README.md
  docker-compose.yml
Labels: dependencies

#63 Update dependencies of ESLint plugin
  .github/workflows/ci.yml
  README.md
  eslint-plugin/.yarn/releases/yarn-4.1.1.cjs
  eslint-plugin/.yarn/releases/yarn-4.6.0.cjs
  eslint-plugin/.yarnrc.yml
  eslint-plugin/README.md
  eslint-plugin/docs/rules/no-import-all-from-library.md
  eslint-plugin/package.json
  eslint-plugin/tests/lib/rules/prefer-collections-with-pagination.js
  eslint-plugin/yarn.lock
Labels: dependencies, 🏗️ refactoring

#64 Fix eslint-plugin with SonarQube 25
  .gitignore
  eslint-plugin/.gitignore
  eslint-plugin/dist/rules.js
  eslint-plugin/package.json
  eslint-plugin/tests/dist/rules.test.js
  sonar-project.properties
Labels: 💉 bug: confirmed

#40 Ec36 avoid autoplay
  CHANGELOG.md
  eslint-plugin/README.md
  eslint-plugin/docs/rules/avoid-autoplay.md
  eslint-plugin/lib/rules/avoid-autoplay.js
  eslint-plugin/tests/lib/rules/avoid-autoplay.js
  sonar-plugin/pom.xml
  sonar-plugin/src/main/java/org/greencodeinitiative/creedengo/javascript/CheckList.java
  sonar-plugin/src/main/java/org/greencodeinitiative/creedengo/javascript/checks/AvoidAutoPlay.java
  sonar-plugin/src/main/resources/org/greencodeinitiative/creedengo/profiles/javascript_profile.json
Labels: 🗃️ rule, 🏆 challenge 🏆
